class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'appName': 'HouseApp',
      'tagline': 'Find Your Next Home Easily',
      'subTagline': 'Verified houses and direct landlord contacts',
      'continueAsTenant': 'Continue as Tenant',
      'continueAsLandlord': 'Continue as Landlord',
      'searchHint': 'Search neighborhoods, landmarks, apartments...',
      'premiumContact': 'Unlock landlord contacts for 5,000 XAF/month',
      'subscribe': 'Subscribe Now',
      'mtn': 'MTN Mobile Money',
      'orange': 'Orange Money',
      'noResults': 'No results found',
      'emptyFavorites': 'Save your dream homes here',
      'emptyMessages': 'No messages yet',
      'emptyListings': 'No listings available',
      'verifyAccount': 'Verify your account',
      'enterPhone': 'Enter your phone number',
      'enterOtp': 'Enter verification code',
      'resendOtp': 'Resend code',
      'terms': 'Terms & Conditions',
      'privacy': 'Privacy Policy',
      'language': 'Language',
      'logout': 'Logout',
      'settings': 'Settings',
      'profile': 'Profile',
      'myListings': 'My Listings',
      'paymentHistory': 'Payment History',
      'subscription': 'Subscription',
      'favorites': 'Favorites',
      'messages': 'Messages',
      'home': 'Home',
      'explore': 'Explore',
      'admin': 'Admin',
      'approve': 'Approve',
      'reject': 'Reject',
      'analytics': 'Analytics',
      'revenue': 'Revenue',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'wifi': 'WiFi',
      'water': 'Water',
      'electricity': 'Electricity',
      'parking': 'Parking',
      'verified': 'Verified',
      'unverified': 'Unverified',
      'premium': 'Premium',
      'fastRent': 'Fast Rent',
      'newListing': 'New',
      'studio': 'Studio',
      'apartment': 'Apartment',
      'furnished': 'Furnished',
      'cheap': 'Cheap',
      'luxury': 'Luxury',
      'student': 'Student',
      'sortBy': 'Sort by',
      'cheapest': 'Cheapest',
      'newest': 'Newest',
      'closest': 'Closest',
      'mostPopular': 'Most Popular',
      'priceRange': 'Price Range',
      'filters': 'Filters',
      'clearAll': 'Clear All',
      'apply': 'Apply',
      'save': 'Save',
      'share': 'Share',
      'call': 'Call',
      'whatsapp': 'WhatsApp',
      'unlockContact': 'Unlock Contact',
      'similarListings': 'Similar Listings',
      'typeMessage': 'Type a message...',
      'online': 'Online',
      'typing': 'Typing...',
      'subscriptionManagement': 'Subscription Management',
      'premiumMember': 'Premium Member',
      'expiresIn': 'Expires in',
      'days': 'days',
      'selectProvider': 'Select Payment Provider',
      'enterMtnPhone': 'Enter MTN phone number',
      'enterOrangePhone': 'Enter Orange phone number',
      'payNow': 'Pay Now',
      'paymentSuccess': 'Payment Successful!',
      'paymentProcessing': 'Processing payment...',
      'paymentFailed': 'Payment failed',
      'tryAgain': 'Try Again',
      'pendingApproval': 'Pending Approval',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'totalUsers': 'Total Users',
      'activeSubscriptions': 'Active Subscriptions',
      'monthlyRevenue': 'Monthly Revenue',
      'conversionRate': 'Conversion Rate',
      'viewAll': 'View All',
      'grid': 'Grid',
      'list': 'List',
      'compare': 'Compare',
      'notes': 'Notes',
      'remove': 'Remove',
      'organize': 'Organize',
      'collections': 'Collections',
      'recentSearches': 'Recent Searches',
      'trendingNeighborhoods': 'Trending Neighborhoods',
      'voiceSearch': 'Voice Search',
      'waterReliability': 'Water Reliability',
      'electricityStability': 'Electricity Stability',
      'roadAccessibility': 'Road Accessibility',
      'floodRisk': 'Flood Risk',
      'internetQuality': 'Internet Quality',
      'securityLevel': 'Security Level',
      'houseRules': 'House Rules',
      'description': 'Description',
      'amenities': 'Amenities',
      'location': 'Location',
      'contactLandlord': 'Contact Landlord',
      'responseTime': 'Response time',
      'listingsCount': 'Listings',
      'notifications': 'Notifications',
      'darkMode': 'Dark Mode',
      'privacySettings': 'Privacy',
      'logoutConfirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'noInternet': 'No internet connection',
      'loading': 'Loading...',
      'error': 'An error occurred',
    },
    'fr': {
      'appName': 'HouseApp',
      'tagline': 'Trouvez Votre Prochain Logement Facilement',
      'subTagline': 'Maisons vérifiées et contacts directs avec les propriétaires',
      'continueAsTenant': 'Continuer comme Locataire',
      'continueAsLandlord': 'Continuer comme Propriétaire',
      'searchHint': 'Rechercher quartiers, monuments, appartements...',
      'premiumContact': 'Débloquez les contacts des propriétaires pour 5 000 XAF/mois',
      'subscribe': 'S\'abonner',
      'mtn': 'MTN Mobile Money',
      'orange': 'Orange Money',
      'noResults': 'Aucun résultat trouvé',
      'emptyFavorites': 'Enregistrez vos logements de rêve ici',
      'emptyMessages': 'Aucun message pour le moment',
      'emptyListings': 'Aucune annonce disponible',
      'verifyAccount': 'Vérifiez votre compte',
      'enterPhone': 'Entrez votre numéro de téléphone',
      'enterOtp': 'Entrez le code de vérification',
      'resendOtp': 'Renvoyer le code',
      'terms': 'Conditions d\'utilisation',
      'privacy': 'Politique de confidentialité',
      'language': 'Langue',
      'logout': 'Déconnexion',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'myListings': 'Mes annonces',
      'paymentHistory': 'Historique des paiements',
      'subscription': 'Abonnement',
      'favorites': 'Favoris',
      'messages': 'Messages',
      'home': 'Accueil',
      'explore': 'Explorer',
      'admin': 'Administrateur',
      'approve': 'Approuver',
      'reject': 'Rejeter',
      'analytics': 'Analytiques',
      'revenue': 'Revenus',
      'goodMorning': 'Bonjour',
      'goodAfternoon': 'Bon après-midi',
      'goodEvening': 'Bonsoir',
      'bedrooms': 'Chambres',
      'bathrooms': 'Salles de bain',
      'wifi': 'WiFi',
      'water': 'Eau',
      'electricity': 'Électricité',
      'parking': 'Stationnement',
      'verified': 'Vérifié',
      'unverified': 'Non vérifié',
      'premium': 'Premium',
      'fastRent': 'Location Rapide',
      'newListing': 'Nouveau',
      'studio': 'Studio',
      'apartment': 'Appartement',
      'furnished': 'Meublé',
      'cheap': 'Pas cher',
      'luxury': 'Luxe',
      'student': 'Étudiant',
      'sortBy': 'Trier par',
      'cheapest': 'Moins cher',
      'newest': 'Plus récent',
      'closest': 'Plus proche',
      'mostPopular': 'Plus populaire',
      'priceRange': 'Prix',
      'filters': 'Filtres',
      'clearAll': 'Tout effacer',
      'apply': 'Appliquer',
      'save': 'Enregistrer',
      'share': 'Partager',
      'call': 'Appeler',
      'whatsapp': 'WhatsApp',
      'unlockContact': 'Débloquer le contact',
      'similarListings': 'Annonces similaires',
      'typeMessage': 'Écrire un message...',
      'online': 'En ligne',
      'typing': 'Écrit...',
      'subscriptionManagement': 'Gestion de l\'abonnement',
      'premiumMember': 'Membre Premium',
      'expiresIn': 'Expire dans',
      'days': 'jours',
      'selectProvider': 'Choisissez le moyen de paiement',
      'enterMtnPhone': 'Entrez le numéro MTN',
      'enterOrangePhone': 'Entrez le numéro Orange',
      'payNow': 'Payer',
      'paymentSuccess': 'Paiement réussi !',
      'paymentProcessing': 'Traitement du paiement...',
      'paymentFailed': 'Échec du paiement',
      'tryAgain': 'Réessayer',
      'pendingApproval': 'En attente',
      'approved': 'Approuvé',
      'rejected': 'Rejeté',
      'totalUsers': 'Utilisateurs',
      'activeSubscriptions': 'Abonnements actifs',
      'monthlyRevenue': 'Revenu mensuel',
      'conversionRate': 'Taux de conversion',
      'viewAll': 'Voir tout',
      'grid': 'Grille',
      'list': 'Liste',
      'compare': 'Comparer',
      'notes': 'Notes',
      'remove': 'Supprimer',
      'organize': 'Organiser',
      'collections': 'Collections',
      'recentSearches': 'Recherches récentes',
      'trendingNeighborhoods': 'Quartiers populaires',
      'voiceSearch': 'Recherche vocale',
      'waterReliability': 'Fiabilité de l\'eau',
      'electricityStability': 'Stabilité électrique',
      'roadAccessibility': 'Accessibilité routière',
      'floodRisk': 'Risque d\'inondation',
      'internetQuality': 'Qualité Internet',
      'securityLevel': 'Niveau de sécurité',
      'houseRules': 'Règles de la maison',
      'description': 'Description',
      'amenities': 'Équipements',
      'location': 'Emplacement',
      'contactLandlord': 'Contacter le propriétaire',
      'responseTime': 'Temps de réponse',
      'listingsCount': 'Annonces',
      'notifications': 'Notifications',
      'darkMode': 'Mode sombre',
      'privacySettings': 'Confidentialité',
      'logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'noInternet': 'Pas de connexion internet',
      'loading': 'Chargement...',
      'error': 'Une erreur est survenue',
    },
  };

  String translate(String key) {
    return _localizedStrings[locale]?[key] ?? _localizedStrings['en']?[key] ?? key;
  }

  static AppLocalizations of(String locale) => AppLocalizations(locale);
}
